### ISSUE TITLE
nomDuPort ?

### ISSUE THREAD

**Issue by JohnWBour** [saniho/apiMareeInfo#16]
Bonjour,

Je viens d'installer le sensor pour Arromanches (http://maree.info/27)
- platform: apiMareeInfo
  code: 27
  latitude: 49.350000
  longitude: -0.616667
  scan_interval: 120

Et ne voyant pas le sensor, j'ai investigué pour identifier un message comme quoi il ne lit pas le nom du port (Les coordonnées GPS sont celles de maree.info transformées via GMaps)

Une idée ?

```
2022-07-17 16:20:03 WARNING (SyncWorker_0) [apiMareeInfo] -update possible- on lance
2022-07-17 16:20:07 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up apiMareeInfo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apiMareeInfo/sensor.py", line 89, in setup_platform
    myPort.update()
  File "/config/custom_components/apiMareeInfo/sensor.py", line 62, in update
    self._myMaree.getinformationport()
  File "/config/custom_components/apiMareeInfo/apiMareeInfo.py", line 86, in getinformationport
    self._nomDuPort = jsondata["contenu"]["marees"][0]['lieu']
IndexError: list index out of range
```

**Comment by saniho** [comment]
essaye ave ces coordonnées : 
265 Arromanches 49.3344 -0.664167

**Comment by JohnWBour** [comment]
Super, merci beaucoup 
Ça a l’air de fonctionner 😉
