### ISSUE TITLE
Sensor ne fonctionne plus suite MAJ HA

### ISSUE THREAD

**Issue by Antoine1-byte** [saniho/apiMareeInfo#32]
Bonjour,

J'ai installé l'integration plus tôt cette semaine.
Cette dernière fonctionnait très bien puis, depuis deux / trois jours, le sensor ne remonte plus d'info:

`- platform: apiMareeInfo
  code: 124
  latitude: 50.14
  longitude: 1.28
  scan_interval: 120
  `
![image](https://github.com/user-attachments/assets/78fd5113-2ccc-4b7a-b8ac-ddaddd74e4d2)

Le message d'alerte dans les logs HA:
`Enregistreur: homeassistant.helpers.entity
Source: helpers/entity.py:942
S'est produit pour la première fois: 00:06:42 (1 occurrences)
Dernier enregistrement: 00:06:42

Update for sensor.myport_124_mareedujour fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 184, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiMareeInfo/sensor.py", line 146, in _update
    self._myPort.update()
  File "/config/custom_components/apiMareeInfo/sensor.py", line 67, in update
    self._myMaree.getinformationport(origine=self._origine)
  File "/config/custom_components/apiMareeInfo/apiMareeInfo.py", line 150, in getinformationport
    if len( jsondata["contenu"]["marees"]) == 0:
            ~~~~~~~~^^^^^^^^^^^
KeyError: 'contenu'

Il y a eu une ou deux MAJ de HA cette semaine (2024.8 et 2024.8.1), j'ignore si il y a un lien mais c'est tout ce que je vois comme explication dans l'immédiat...

D'avance merci pour votre aide,

Antoine

**Comment by Antoine1-byte** [comment]
Bonjour

Problème résolu en changeant légèrement les coordonnées GPS du lieu choisi...
